version: '2'
services:
  nginx:
   image: nginx:1.15.6-alpine
   ports:
     - '80:80'
     - '443:443'
   volumes:
     - ./laravel:/var/www/html:cached
     - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
     - laravel
  

  laravel:
   build: ./docker/php74
   volumes:
     - ./laravel:/var/www/html:cached
   depends_on:
     - db
     - redis

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      TZ: "Asia/Tokyo"


  redis:
    image: redis:4.0-alpine
    restart: always
    ports:
      - '6379:6379'
